# This file was *autogenerated* from the file mms.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_2p5 = RealNumber('2.5'); _sage_const_1p0 = RealNumber('1.0'); _sage_const_1p2 = RealNumber('1.2'); _sage_const_0p0 = RealNumber('0.0'); _sage_const_0p5 = RealNumber('0.5')
def function(phi_0, phi_x, f_sin_x, f_cos_x, alpha_x):
    
    f_0 = phi_0 
    f_x = phi_x*(f_sin_x*sin(alpha_x*x) + f_cos_x*cos(alpha_x*x)) 
    f = f_0 + f_x
    return f

u = function(_sage_const_2p5 , _sage_const_1p0 , _sage_const_0p0 , _sage_const_1p0 , _sage_const_1p0 )
h = function(_sage_const_1p2 , _sage_const_1p0 , _sage_const_1p0 , _sage_const_0p0 , _sage_const_1p0 )

q = u*h

Sh = diff(q,x)
Sq = diff(q**_sage_const_2 /h + _sage_const_0p5 *h*h, x)

print "def u_s():"
print "    return '", str(u.simplify()).replace("000000000000", "").replace("x", "x[0]").replace("y", "x[1]"), "'"
print "def h_s():"
print "    return '", str(h.simplify()).replace("000000000000", "").replace("x", "x[0]").replace("y", "x[1]"), "'"
print "def q_s():"
print "    return '", str(q.simplify()).replace("000000000000", "").replace("x", "x[0]").replace("y", "x[1]"), "'"
print "def Sh_s():"
print "    return '", str(Sh.simplify()).replace("000000000000", "").replace("x", "x[0]").replace("y", "x[1]"), "'"
print "def Sq_s():"
print "    return '", str(Sq.simplify()).replace("000000000000", "").replace("x", "x[0]").replace("y", "x[1]"), "'"
