# This file was *autogenerated* from the file Sediment_MMS.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1p8 = RealNumber('1.8'); _sage_const_2 = Integer(2); _sage_const_2p1 = RealNumber('2.1'); _sage_const_1p0 = RealNumber('1.0'); _sage_const_1p3 = RealNumber('1.3'); _sage_const_5p2 = RealNumber('5.2'); _sage_const_1p7 = RealNumber('1.7'); _sage_const_0p1 = RealNumber('0.1'); _sage_const_0p0 = RealNumber('0.0'); _sage_const_3p7 = RealNumber('3.7')
y = var('y')

def function(phi_0, phi_x, phi_y, phi_xy, 
             f_sin_x, f_cos_x, f_sin_y, f_cos_y, f_sin_xy, f_cos_xy, 
             alpha_x, alpha_y, alpha_xy):
    
    f_0 = phi_0 
    f_x = phi_x*(f_sin_x*sin(alpha_x*x) + f_cos_x*cos(alpha_x*x)) 
    f_y = phi_y*(f_sin_y*sin(alpha_y*y) + f_cos_y*cos(alpha_y*y)) 
    f_xy = phi_xy*(f_sin_xy*sin(alpha_xy*x*y/pi) + f_cos_xy*cos(alpha_xy*x*y/pi)) 
    f = f_0 + f_x + f_y + f_xy
    return f

u = function(_sage_const_0p0 , _sage_const_1p0 , _sage_const_1p0 , _sage_const_0p0 , 
             _sage_const_1p0 , _sage_const_0p0 , _sage_const_1p0 , _sage_const_0p0 , _sage_const_1p0 , _sage_const_0p0 ,
             _sage_const_1p0 , _sage_const_1p0 , _sage_const_1p0 )
p = function(-_sage_const_1p0 , _sage_const_1p0 , _sage_const_1p0 , _sage_const_1p0 ,
             _sage_const_1p0 , _sage_const_0p0 , _sage_const_0p0 , _sage_const_1p0 , _sage_const_1p0 , _sage_const_0p0 ,
             _sage_const_1p0 , _sage_const_1p0 , _sage_const_1p0 )
c = function(_sage_const_5p2 , -_sage_const_1p8 , -_sage_const_1p3 , _sage_const_3p7 , 
               _sage_const_1p0 , _sage_const_0p0 , _sage_const_0p0 , _sage_const_1p0 , _sage_const_1p0 , _sage_const_0p0 ,
               _sage_const_1p7 , _sage_const_2p1 , _sage_const_1p3 )
u = sin(x)*cos(y)
v = integral(-diff(u,x),y)  # divergence free
nu = _sage_const_1p0 
kappa = _sage_const_0p1 

tau_xx = _sage_const_2 *diff(u,x)            *nu
tau_xy = diff(u,y) + diff(v,x)  *nu
tau_yy = _sage_const_2 *diff(v,y)            *nu
tau_yx = diff(u,y) + diff(v,x)  *nu

Su = u*diff(u,x) + v*diff(u,y) - diff(tau_xx, x) - diff(tau_xy, y) + diff(p,x)  
Sv = u*diff(v,x) + v*diff(v,y) - diff(tau_yx, x) - diff(tau_yy, y) + diff(p,y)  

Sc = u*diff(c,x) + v*diff(c,y) - kappa*diff(c, x, x) - kappa*diff(c, y, y) 
  
print "#", str(diff(u, x, x) + diff(v, y, y))
print "def u_s():"
print "    return '", str(u.simplify()).replace("000000000000", "").replace("x", "x[0]").replace("y", "x[1]"), "'"
print "def v_s():"
print "    return '", str(v.simplify()).replace("000000000000", "").replace("x", "x[0]").replace("y", "x[1]"), "'"
print "def p_s():"
print "    return '", str(p.simplify()).replace("000000000000", "").replace("x", "x[0]").replace("y", "x[1]"), "'"
print "def c_s():"
print "    return '", str(c.simplify()).replace("000000000000", "").replace("x", "x[0]").replace("y", "x[1]"), "'"
print "def u_fs():"
print "    return '", str(Su.simplify()).replace("000000000000", "").replace("x", "x[0]").replace("y", "x[1]"), "'"
print "def v_fs():"
print "    return '", str(Sv.simplify()).replace("000000000000", "").replace("x", "x[0]").replace("y", "x[1]"), "'"
print "def c_fs():"
print "    return '", str(Sc.simplify()).replace("000000000000", "").replace("x", "x[0]").replace("y", "x[1]"), "'"
